# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 11:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('selected_by_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contaminant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_ID', models.CharField(max_length=10)),
                ('short_name', models.CharField(max_length=20)),
                ('long_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence', models.TextField()),
                ('organism', models.CharField(blank=True, max_length=50, null=True)),
                ('organism_pdb', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_code', models.CharField(max_length=4)),
                ('chain', models.CharField(blank=True, max_length=10, null=True)),
                ('domain', models.IntegerField(blank=True, default=None, null=True)),
                ('identity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('architecture', models.CharField(max_length=15)),
                ('coverage', models.IntegerField()),
                ('contaminant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Contaminant')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_group', models.CharField(max_length=15)),
                ('error', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('percent', models.IntegerField(default=None)),
                ('q_factor', models.FloatField(default=None)),
                ('exec_time', models.DurationField(default=datetime.timedelta(0))),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Job')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Pack')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Pack'),
        ),
    ]
