# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 08:45
from __future__ import unicode_literals

import contaminer.models.tools
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('selected_by_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsolete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contaminant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', contaminer.models.tools.UpperCaseCharField(max_length=10)),
                ('short_name', contaminer.models.tools.UpperCaseCharField(max_length=20)),
                ('long_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence', models.TextField()),
                ('organism', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_submitted', models.BooleanField(default=False)),
                ('status_running', models.BooleanField(default=False)),
                ('status_complete', models.BooleanField(default=False)),
                ('status_error', models.BooleanField(default=False)),
                ('status_archived', models.BooleanField(default=False)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('confidential', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_code', contaminer.models.tools.UpperCaseCharField(max_length=4)),
                ('chain', models.CharField(blank=True, max_length=10, null=True)),
                ('domain', models.IntegerField(blank=True, default=None, null=True)),
                ('nb_residues', models.IntegerField()),
                ('identity', contaminer.models.tools.PercentageField()),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('structure', models.CharField(max_length=15)),
                ('contaminant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Contaminant')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.IntegerField()),
                ('contaminant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Contaminant')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contaminant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Contaminant')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_group', models.CharField(max_length=15)),
                ('status_complete', models.BooleanField(default=False)),
                ('status_error', models.BooleanField(default=False)),
                ('percent', contaminer.models.tools.PercentageField(default=None, null=True)),
                ('q_factor', models.FloatField(default=None, null=True)),
                ('exec_time', models.DurationField(default=datetime.timedelta(0))),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Job')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Pack')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Pack'),
        ),
        migrations.AddField(
            model_name='category',
            name='contabase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.ContaBase'),
        ),
    ]
