# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaminer', '0002_job_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_running',
            field=models.BooleanField(default=False),
        ),
    ]
