# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaminer', '0002_job_confidential'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaminant',
            name='publication_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
