# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contaminer', '0003_contaminant_publication_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contaminant',
            name='publication_id',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='contaminant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Contaminant'),
        ),
        migrations.AddField(
            model_name='reference',
            name='contaminant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contaminer.Contaminant'),
        ),
    ]
