# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaminer', '0003_task_status_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaminant',
            name='uniprot_id',
            field=models.CharField(max_length=10),
        ),
    ]
