# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-10 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaminer', '0005_task_r_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaminant',
            name='uniprot_id',
            field=models.CharField(max_length=100),
        ),
    ]
